Emphasize re-register in iOS 13 migration guide
twilio/twilio-voice-ios pull request #19
Opened 2019-09-30 22:21 UTC by bchen-twilio

- [x] I acknowledge that all my contributions will be made under the project's license.

Updates:
- Add code snippet to show how to register when the app is launched.
- Add a paragraph to emphasize the importance of update and re-register when the app is launched.

2019-09-30 22:29 UTC, idelgado requested changes

2019-09-30 22:29 UTC, idelgado commented on iOS-13-Migration-Guide.md
> +This ensures that your app no longer receives “cancel” push notifications. Please note that if the app is updated but never launched for the execution of the above, the mobile client will still recei
I would still keep this paragraph before the code snippet. Explaining the why should be first.

2019-09-30 22:29 UTC, idelgado commented on iOS-13-Migration-Guide.md
> +This ensures that your app no longer receives “cancel” push notifications. Please note that if the app is updated but never launched for the execution of the above, the mobile client will still recei
I would create a section under the code snippet that describes what to do to manage the corner case where the app has not been launched yet. Additionally in this section I would actually provide a code snippet with the recommended workaround.

2019-09-30 23:00 UTC, piyushtank requested changes

2019-09-30 23:00 UTC, piyushtank commented on iOS-13-Migration-Guide.md
> +	    self.deviceTokenString = [credentials.token description];
I guess we should use the iOS 13 way of getting the device token here?

2019-09-30 23:00 UTC, piyushtank commented on iOS-13-Migration-Guide.md
> +A "call" push notification, when passed to `[TwilioVoice handleNotification:delegate:delegateQueue:]`, will return a `TVOCallInvite` object to you synchronously via the `[TVONotificationDelegate call
suggestion -
```
A "call" push notification, when passed to `[TwilioVoice handleNotification:delegate:delegateQueue:]`, will return a `TVOCallInvite` object to you synchronously via the `[TVONotificationDelegate callInviteReceived:]` delegate callback. A `TVOCancelledCallInvite` will be raised asynchronously via `[TVONotificationDelegate cancelledCallInviteReceived:error:]` if any of the following events occur:
```

2019-09-30 23:40 UTC, idelgado requested changes

2019-09-30 23:40 UTC, idelgado commented on iOS-13-Migration-Guide.md
> +	```
`.objective-c`

2019-09-30 23:40 UTC, idelgado commented on iOS-13-Migration-Guide.md
> +	```
`.swift`

2019-09-30 23:44 UTC, idelgado reviewed
Once @piyushtank has reviewed this you need to update the 2.1.0 section of the migration guide with similar guidance.

2019-10-01 01:22 UTC, idelgado approved these changes

2019-10-01 19:49 UTC, piyushtank requested changes

2019-10-01 19:49 UTC, piyushtank commented on iOS-13-Migration-Guide.md
> +        self.deviceTokenString = [NSString stringWithFormat:@"<%08x %08x %08x %08x %08x %08x %08x %08x>",
formating.. use space vs tabs I guess

2019-10-01 19:49 UTC, piyushtank commented on iOS-13-Migration-Guide.md
> +	        CXCallUpdate *callUpdate = [[CXCallUpdate alloc] init];
formatting

2019-10-01 19:49 UTC, piyushtank commented on iOS-13-Migration-Guide.md
> +	        return;
formatting..

2019-10-01 19:49 UTC, piyushtank commented on iOS-13-Migration-Guide.md
> +            let callHandle = CXHandle(type: .generic, value: "alice")
formatting

2019-10-01 19:49 UTC, piyushtank commented on iOS-13-Migration-Guide.md
> +            callKitProvider.reportNewIncomingCall(with: nil, update: callUpdate) { error in
This workaround has a risk of app store rejection. We are suggesting that report a call and end immediately where we are not violating Apple's guideline.

Lets use the workaround we are suggesting here - https://github.com/twilio/voice-quickstart-swift/issues/251
cc @idelgado @bchen-twilio

2019-10-01 19:49 UTC, piyushtank commented on iOS-13-Migration-Guide.md
> +            voipRegistry.desiredPushTypes = Set([PKPushType.voIP])
formatting

2019-10-01 19:49 UTC, piyushtank commented on iOS-13-Migration-Guide.md
> +            TwilioVoice.register(withAccessToken: accessToken, deviceToken: deviceToken) { (error) in
formatting

2019-10-01 19:49 UTC, piyushtank commented on iOS-13-Migration-Guide.md
> +            [self.callKitCallController requestTransaction:transaction completion:^(NSError *error) {
dispatch_async(..) here? This should be invoked on the next tick.

2019-10-01 19:56 UTC, piyushtank approved these changes

2019-10-01 20:05 UTC, idelgado approved these changes

2019-10-01 20:08 UTC, merged